publishMac commit from mace - 2025-01-20.

diff --git a/mace b/mace
--- a/mace
+++ b/mace
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-version="0.1.165"
+version="0.1.166"
 
 script_name=$(basename "$0")
 jim928Path=$(brew --repo)/Library/Taps/jim928
@@ -16,7 +16,7 @@ find_key() {
 	local key="$1"
 	local pattern="|$key:"
 	local start=${ENCRYPTED_SSH_KEYS#*$pattern}
-	if [[ "$start" != "$ENCRYPTED_SSH_KEYS" ]]; then
+	if [[ $start != "$ENCRYPTED_SSH_KEYS" ]]; then
 		return 0
 	fi
 	return 1
@@ -30,7 +30,7 @@ update_key() {
 	current_keys="${ENCRYPTED_SSH_KEYS//${key}:[^|]*/}"
 
 	# 添加新的键值对
-	if [[ -n "$current_keys" ]]; then
+	if [[ -n $current_keys ]]; then
 		current_keys+="|"
 	fi
 	current_keys+="$key:$value"
@@ -49,7 +49,7 @@ inject_key_to_script() {
 	# 移除旧的键值对
 	current_keys="${current_keys//${key}:[^|]*/}"
 	# 添加新的键值对
-	if [[ -n "$current_keys" ]]; then
+	if [[ -n $current_keys ]]; then
 		current_keys+="|"
 	fi
 	current_keys+="$key:$value"
@@ -163,127 +163,136 @@ testFunc() {
 
 #################### publish new version of mace ####################
 publishNewVersion() {
-	cd "$maceWorkDir/mace" || echo "cd to path failed :$maceWorkDir/mace"
+    # Check if shfmt is installed, and install it if not
+    if ! command -v shfmt &> /dev/null; then
+        echo "shfmt not found, installing..."
+        brew install shfmt
+    fi
 
-	# 删除所有本地标签
-	git tag -l | xargs git tag -d >/dev/null 2>&1
+    # Format the mace file
+    shfmt -w -s mace
 
-	# 拉取最新标签
-	git fetch --tags >/dev/null 2>&1
-	git pull
+    cd "$maceWorkDir/mace" || echo "cd to path failed :$maceWorkDir/mace"
 
-	# 修改版本号
-	# 获取当前文件夹下 mace 文件的版本号
-	current_version=$(grep 'version=' mace | sed -n 's/version="\([^"]*\)".*/\1/p' | head -n 1)
+    # 删除所有本地标签
+    git tag -l | xargs git tag -d >/dev/null 2>&1
 
-	# 递增版本号
-	new_version=$(awk -F. -v OFS=. '{print $1,$2,$3+1}' <<<"$current_version")
+    # 拉取最新标签
+    git fetch --tags >/dev/null 2>&1
+    git pull
 
-	# 使用 sed 命令替换文件中的 version 变量
-	sed -i '' "s/version=\"$current_version\"/version=\"$new_version\"/" mace
+    # 修改版本号
+    # 获取当前文件夹下 mace 文件的版本号
+    current_version=$(grep 'version=' mace | sed -n 's/version="\([^"]*\)".*/\1/p' | head -n 1)
 
-	# 输出新版本号``
-	echo "Old Version: $current_version"
-	echo "New Version: $new_version"
+    # 递增版本号
+    new_version=$(awk -F. -v OFS=. '{print $1,$2,$3+1}' <<<"$current_version")
 
-	# 获取当前日期
-	current_date=$(date +"%Y-%m-%d")
-	git add .
-	git commit -m "publishMac commit from mace - ${current_date}." -a
-	#  git push "${maceGitUrl}" HEAD:master
+    # 使用 sed 命令替换文件中的 version 变量
+    sed -i '' "s/version=\"$current_version\"/version=\"$new_version\"/" mace
 
-	# 创建新 tag
-	git tag -a "$new_version" -m "$new_version"
+    # 输出新版本号``
+    echo "Old Version: $current_version"
+    echo "New Version: $new_version"
 
-	# 推送所有分支和标签
-	git push "${maceGitUrl}" HEAD:master
-	echo "push mace changes to $maceGitUrl done"
-	git push --tags "${maceGitUrl}"
-	echo "push mace tags to $maceGitUrl done"
+    # 获取当前日期
+    current_date=$(date +"%Y-%m-%d")
+    git add .
+    git commit -m "publishMac commit from mace - ${current_date}." -a
+    #  git push "${maceGitUrl}" HEAD:master
 
-	########## release new version to github ########
-	# Replace with your GitHub username and repository name
-	USERNAME="jim928"
-	REPO="mace"
+    # 创建新 tag
+    git tag -a "$new_version" -m "$new_version"
 
-	# Replace with the tag name you want to create a release from
-	TAG="$new_version"
+    # 推送所有分支和标签
+    git push "${maceGitUrl}" HEAD:master
+    echo "push mace changes to $maceGitUrl done"
+    git push --tags "${maceGitUrl}"
+    echo "push mace tags to $maceGitUrl done"
 
-	RELEASE_NOTES="Release notes for version $TAG"
+    ########## release new version to github ########
+    # Replace with your GitHub username and repository name
+    USERNAME="jim928"
+    REPO="mace"
 
-	echo "Creating GitHub release..."
-	response=$(curl -s -X POST \
-		-H "Accept: application/vnd.github.v3+json" \
-		-H "Content-Type: application/json" \
-		"https://api.github.com/repos/$USERNAME/$REPO/releases" \
-		-d "{\"tag_name\":\"$TAG\",\"name\":\"$TAG\",\"body\":\"$RELEASE_NOTES\"}")
+    # Replace with the tag name you want to create a release from
+    TAG="$new_version"
 
-	# Print the response from GitHub API
-	echo "$response"
+    RELEASE_NOTES="Release notes for version $TAG"
 
-	# Extract the release ID from the response
-	release_id=$(echo "$response" | jq -r '.id')
-	echo "Release ID: $release_id"
+    echo "Creating GitHub release..."
+    response=$(curl -s -X POST \
+        -H "Accept: application/vnd.github.v3+json" \
+        -H "Content-Type: application/json" \
+        "https://api.github.com/repos/$USERNAME/$REPO/releases" \
+        -d "{\"tag_name\":\"$TAG\",\"name\":\"$TAG\",\"body\":\"$RELEASE_NOTES\"}")
 
-	# 提取源代码（tar.gz）文件的下载链接
-	download_url="https://github.com/jim928/mace/archive/refs/tags/$new_version.tar.gz"
+    # Print the response from GitHub API
+    echo "$response"
 
-	# 打印下载链接
-	echo "源代码下载链接: $download_url"
+    # Extract the release ID from the response
+    release_id=$(echo "$response" | jq -r '.id')
+    echo "Release ID: $release_id"
 
-	######## 开始brew 发布 流程 ########
-	# Formula name
-	formula_name="mace"
+    # 提取源代码（tar.gz）文件的下载链接
+    download_url="https://github.com/jim928/mace/archive/refs/tags/$new_version.tar.gz"
 
-	# Source URL
-	source_url="$download_url"
+    # 打印下载链接
+    echo "源代码下载链接: $download_url"
 
-	######## 生成 mace.rb 文件 ########
+    ######## 开始brew 发布 流程 ########
+    # Formula name
+    formula_name="mace"
 
-	# Homebrew Core Formula directory
-	formula_directory="$HOME/.mace/homebrew-mace"
+    # Source URL
+    source_url="$download_url"
 
-	# if formula_directory not exist, clone it else update it
-	if [ ! -d "$formula_directory" ]; then
-		echo "homebrew-mace directory does not exist. Cloning..."
-		mkdir -p "$formula_directory"
-		git clone "${homebrew_mace_url}" "$formula_directory"
-	else
-		echo "homebrew-mace directory exists. Updating..."
-		cd "$formula_directory" || {
-			echo "cd to path failed: $formula_directory"
-			exit 1
-		}
-		git fetch && git pull
-	fi
+    ######## 生成 mace.rb 文件 ########
 
-	cd "$formula_directory" || {
-		echo "cd to path failed: $formula_directory"
-		exit 1
-	}
+    # Homebrew Core Formula directory
+    formula_directory="$HOME/.mace/homebrew-mace"
 
-	mace_formula_path="$formula_directory/$formula_name.rb"
+    # if formula_directory not exist, clone it else update it
+    if [ ! -d "$formula_directory" ]; then
+        echo "homebrew-mace directory does not exist. Cloning..."
+        mkdir -p "$formula_directory"
+        git clone "${homebrew_mace_url}" "$formula_directory"
+    else
+        echo "homebrew-mace directory exists. Updating..."
+        cd "$formula_directory" || {
+            echo "cd to path failed: $formula_directory"
+            exit 1
+        }
+        git fetch && git pull
+    fi
 
-	# Create mace.rb with SHA256 checksum
-	echo "class Mace < Formula" >"$mace_formula_path"
-	echo "  desc \"Your description here\"" >>"$mace_formula_path"
-	echo "  homepage \"https://github.com/jim928/mace\"" >>"$mace_formula_path"
-	echo "  url \"$source_url\"" >>"$mace_formula_path"
-	echo "  sha256 \"$(curl -Ls "$source_url" | shasum -a 256 | cut -d ' ' -f 1)\"" >>"$mace_formula_path"
-	echo "" >>"$mace_formula_path"
-	echo "  # ... 其他 Formula 配置信息 ..." >>"$mace_formula_path"
-	echo "" >>"$mace_formula_path"
-	echo "  def install" >>"$mace_formula_path"
-	echo "    bin.install 'mace'" >>"$mace_formula_path"
-	echo "  end" >>"$mace_formula_path"
-	echo "end" >>"$mace_formula_path"
+    cd "$formula_directory" || {
+        echo "cd to path failed: $formula_directory"
+        exit 1
+    }
 
-	# Print the path to the created mace.rb file
-	echo "Formula file created at: $mace_formula_path"
+    mace_formula_path="$formula_directory/$formula_name.rb"
 
-	git add .
-	git commit -m "publish mace.rb $new_version commit from mace}." -a
-	git push "${homebrew_mace_url}" HEAD:master
+    # Create mace.rb with SHA256 checksum
+    echo "class Mace < Formula" >"$mace_formula_path"
+    echo '  desc "Your description here"' >>"$mace_formula_path"
+    echo '  homepage "https://github.com/jim928/mace"' >>"$mace_formula_path"
+    echo "  url \"$source_url\"" >>"$mace_formula_path"
+    echo "  sha256 \"$(curl -Ls "$source_url" | shasum -a 256 | cut -d ' ' -f 1)\"" >>"$mace_formula_path"
+    echo "" >>"$mace_formula_path"
+    echo "  # ... 其他 Formula 配置信息 ..." >>"$mace_formula_path"
+    echo "" >>"$mace_formula_path"
+    echo "  def install" >>"$mace_formula_path"
+    echo "    bin.install 'mace'" >>"$mace_formula_path"
+    echo "  end" >>"$mace_formula_path"
+    echo "end" >>"$mace_formula_path"
+
+    # Print the path to the created mace.rb file
+    echo "Formula file created at: $mace_formula_path"
+
+    git add .
+    git commit -m "publish mace.rb $new_version commit from mace}." -a
+    git push "${homebrew_mace_url}" HEAD:master
 }
 
 ################ upgrade mace version from brew ###############
@@ -883,12 +892,12 @@ functions=(
 
 while (($# > 0)); do
 	# 如果参数以 .rar 结尾，直接调用 rar() 方法
-	if [[ "$1" == *.rar ]]; then
+	if [[ $1 == *.rar ]]; then
 		rar "$1"
 		exit
 	fi
 
-	if [[ "$1" == "-v" ]]; then
+	if [[ $1 == "-v" ]]; then
 		echo "${version}"
 		exit
 	fi
@@ -899,7 +908,7 @@ while (($# > 0)); do
 		func="${entry#*:}"
 
 		# 如果参数匹配，则执行相应的函数并退出循环
-		if [[ "$1" == "$param" ]]; then
+		if [[ $1 == "$param" ]]; then
 			$func "$@"
 			exit
 		fi
